#!/usr/bin/env bash

# Function to display information about a subdomain
display_info() {
    domain=$1
    subdomain=$2

    # Use dig to get information about the subdomain
    result=$(dig ${subdomain}.${domain} | grep -A1 'ANSWER SECTION:')

    # Extract relevant information using awk
    subdomain_info=$(echo "${result}" | awk '/;; ANSWER SECTION:/ {getline; print}')

    # Extract the record type and destination IP
    record_type=$(echo "${subdomain_info}" | awk '{print $4}')
    destination=$(echo "${subdomain_info}" | awk '{print $5}')

    # Display the information
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

# Main script
if [ "$#" -eq 1 ]; then
    # Display information for default subdomains
    display_info $1 "www"
    display_info $1 "lb-01"
    display_info $1 "web-01"
    display_info $1 "web-02"
elif [ "$#" -eq 2 ]; then
    # Display information for the specified subdomain
    display_info $1 $2
else
    # Display usage message if incorrect number of arguments
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
