#!/usr/bin/env bash

domain_information() {
    local domain="$1"
    local subdomain="$2"

    line=$(dig +short "$subdomain.$domain")

    if [ -n "$line" ]; then
        echo "$subdomain $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
    else
        echo "The subdomain $subdomain does not exist."
    fi
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
