#!/usr/bin/env bash
#!/usr/bin/env bash
# Transfers a file from our client to a server

# Check if the number of parameters is not equal to 4
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Transfer the file using scp with options
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/ && echo "File successfully transferred to $3@$2:~/"
fi
