#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80

# Update package list and install Nginx with the -y flag for non-interactive installation
apt-get -y update
apt-get -y install nginx

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Create a default index.html file
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# Start Nginx service
if service nginx start; then
    echo "Nginx started successfully."
else
    echo "Error: Nginx failed to start. Please check logs for more information."
fi
