#!/usr/bin/env bash
# This script installs and configures nginx

# Web servers are the piece of software generating and serving HTML pages, let’s install one!

# Requirements:

# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

# apt update
apt-get update

# Install nginx
apt-get install -y nginx

# allow firewall
ufw allow 'Nginx HTTP'

# listen on port 80
sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default

# create index.html
echo "Hello World!" > /var/www/html/index.html

# restart nginx
service nginx restart
