#!/usr/bin/env bash
# This script installs and configures nginx

# Update package list
apt update

# Install nginx
apt install -y nginx

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Ensure Nginx is listening on port 80
server_block_path="/etc/nginx/sites-available/default"
sed -i 's/listen 80 default_server;/listen 80;/g' "$server_block_path"

# Create a temporary HTML file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart
