#!/usr/bin/env bash
# This script installs and configures nginx

# Update package list
apt update

# Install nginx
apt install -y nginx

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# set 301 redirect
sudo sed -i '/listen 80 default_server/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

# test nginx configuration
nginx -t

# Restart Nginx
service nginx restart
