#!/usr/bin/env bash
# This script installs and configures nginx

# Update package list
apt update

# Install nginx
apt install -y nginx

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Redirect
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Create a temporary HTML file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# page 404
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
