#!/usr/bin/env bash
# This script fulfills the below requirements

# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task

# Update package list
sudo apt update

# Install nginx
sudo apt install -y nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Create directories
sudo mkdir -p /data/web_static/releases/test/
sudo mkdir -p /data/web_static/shared/

# Create a temporary HTML file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html
# Create a custom 404 error page containing the specified string
echo 'Ceci n'"'"'est pas une page' > /usr/share/nginx/html/404.html

# Configure NGINX to use the custom 404 page
sed -i '/server_name _;/a \\n    error_page 404 /404.html;\n    location = /404.html {\n        root /usr/share/nginx/html;\n        internal;\n    }\n    location = /404 {\n        return 404 "Ceci n'"'"'est pas une page";\n    }' /etc/nginx/sites-available/default

echo "Holberton School" | sudo tee /data/web_static/releases/test/index.html

# Create symbolic link
sudo ln -sf /data/web_static/releases/test/ /data/web_static/current

# Change ownership of /data/
sudo chown -R ubuntu:ubuntu /data/

# Update Nginx configuration to serve the content of /data/web_static/current/ to hbnb_static
sudo sed -i "/listen 80 default_server;/a \\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
