#!/bin/bash

# Check if the script is running in Docker
if [ -f "/.dockerenv" ]; then
    echo "Running inside Docker container."
else
    echo "This script should be run inside a Docker container."
    exit 1
fi

# Add entries to /etc/hosts to configure DNS resolution
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Restart networking to apply changes
sudo systemctl restart networking
